//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MyPacket.proto
namespace MyPacket
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequest")]
  public partial class LoginRequest : global::ProtoBuf.IExtensible
  {
    public LoginRequest() {}
    
    private int _PlayerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PlayerId
    {
      get { return _PlayerId; }
      set { _PlayerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Position")]
  public partial class Position : global::ProtoBuf.IExtensible
  {
    public Position() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResult")]
  public partial class LoginResult : global::ProtoBuf.IExtensible
  {
    public LoginResult() {}
    
    private int _PlayerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PlayerId
    {
      get { return _PlayerId; }
      set { _PlayerId = value; }
    }
    private string _PlayerName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PlayerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PlayerName
    {
      get { return _PlayerName; }
      set { _PlayerName = value; }
    }
    private MyPacket.Position _PlayerPos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"PlayerPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MyPacket.Position PlayerPos
    {
      get { return _PlayerPos; }
      set { _PlayerPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatRequest")]
  public partial class ChatRequest : global::ProtoBuf.IExtensible
  {
    public ChatRequest() {}
    
    private int _PlayerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PlayerId
    {
      get { return _PlayerId; }
      set { _PlayerId = value; }
    }
    private string _PlayerMessage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PlayerMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PlayerMessage
    {
      get { return _PlayerMessage; }
      set { _PlayerMessage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatResult")]
  public partial class ChatResult : global::ProtoBuf.IExtensible
  {
    public ChatResult() {}
    
    private string _PlayerName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PlayerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PlayerName
    {
      get { return _PlayerName; }
      set { _PlayerName = value; }
    }
    private string _PlayerMessage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PlayerMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PlayerMessage
    {
      get { return _PlayerMessage; }
      set { _PlayerMessage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveRequest")]
  public partial class MoveRequest : global::ProtoBuf.IExtensible
  {
    public MoveRequest() {}
    
    private int _PlayerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PlayerId
    {
      get { return _PlayerId; }
      set { _PlayerId = value; }
    }
    private MyPacket.Position _PlayerPos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PlayerPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MyPacket.Position PlayerPos
    {
      get { return _PlayerPos; }
      set { _PlayerPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveResult")]
  public partial class MoveResult : global::ProtoBuf.IExtensible
  {
    public MoveResult() {}
    
    private int _PlayerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PlayerId
    {
      get { return _PlayerId; }
      set { _PlayerId = value; }
    }
    private MyPacket.Position _PlayerPos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PlayerPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MyPacket.Position PlayerPos
    {
      get { return _PlayerPos; }
      set { _PlayerPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Depth")]
  public partial class Depth : global::ProtoBuf.IExtensible
  {
    public Depth() {}
    
    private int _Count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Count
    {
      get { return _Count; }
      set { _Count = value; }
    }
    private int _Qty;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Qty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Qty
    {
      get { return _Qty; }
      set { _Qty = value; }
    }
    private float _Price;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Price", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Price
    {
      get { return _Price; }
      set { _Price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Feed")]
  public partial class Feed : global::ProtoBuf.IExtensible
  {
    public Feed() {}
    
    private string _ProductCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ProductCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ProductCode
    {
      get { return _ProductCode; }
      set { _ProductCode = value; }
    }
    private readonly global::System.Collections.Generic.List<MyPacket.Depth> _BidDepth = new global::System.Collections.Generic.List<MyPacket.Depth>();
    [global::ProtoBuf.ProtoMember(2, Name=@"BidDepth", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MyPacket.Depth> BidDepth
    {
      get { return _BidDepth; }
    }
  
    private readonly global::System.Collections.Generic.List<MyPacket.Depth> _AskDepth = new global::System.Collections.Generic.List<MyPacket.Depth>();
    [global::ProtoBuf.ProtoMember(3, Name=@"AskDepth", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MyPacket.Depth> AskDepth
    {
      get { return _AskDepth; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerStatus")]
  public partial class ServerStatus : global::ProtoBuf.IExtensible
  {
    public ServerStatus() {}
    
    private int _SessionCount;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SessionCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SessionCount
    {
      get { return _SessionCount; }
      set { _SessionCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MessageType")]
    public enum MessageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PKT_CS_LOGIN", Value=1)]
      PKT_CS_LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PKT_SC_LOGIN", Value=2)]
      PKT_SC_LOGIN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PKT_CS_CHAT", Value=3)]
      PKT_CS_CHAT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PKT_SC_CHAT", Value=4)]
      PKT_SC_CHAT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PKT_CS_MOVE", Value=5)]
      PKT_CS_MOVE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PKT_SC_MOVE", Value=6)]
      PKT_SC_MOVE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PKT_SC_FEED", Value=7)]
      PKT_SC_FEED = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PKT_CS_SERVER_STATUS", Value=8)]
      PKT_CS_SERVER_STATUS = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PKT_SC_SERVER_STATUS", Value=9)]
      PKT_SC_SERVER_STATUS = 9
    }
  
}